version: '3'

services:

  terrain-server: 

    image: terrain-server:v1.0.0

    build: .

    container_name: terrain-server-container
    
    volumes:
      - ~/Downloads/data:/data

    network_mode: host

    ports:
      - 8000:8000

    environment:
      GPKG_LIST: '[{"id": "meimad", "path": "meimad.gpkg" }]'

    restart: unless-stopped
