{{- if and (.Values.enabled) (.Values.ingress.enabled) -}}
{{- $releaseName := .Release.Name -}}
{{- $serviceName := include "service.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $releaseName }}-nginx-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    {{- if eq .Values.ingress.type "nginx-org" }}
    nginx.org/mergeable-ingress-type: "minion"
    nginx.org/rewrites: 'serviceName={{ $serviceName }}-nginx rewrite=/'
    {{- end }}
    {{- if eq .Values.ingress.type "nginx-kubernetes" }}
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    {{- end }}
    nginx.org/location-snippets: |
      if ($request_method = OPTIONS) {
        return 204;
      }
    {{- if .Values.ingress.cors.enabled }}
      add_header 'Access-Control-Allow-Origin' '{{- .Values.ingress.cors.origin -}}';
      add_header 'Access-Control-Max-Age' 3600;
      add_header 'Access-Control-Expose-Headers' 'Content-Length';
      add_header 'Access-Control-Allow-Headers' '*';
    {{- end }}
spec:
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.ingress.host | quote }}
    secretName: ingress-tls-secret
  {{- end }}
  rules:
  - http:
      paths:
      - path: {{ .Values.ingress.path }}{{- if eq .Values.ingress.type "nginx-kubernetes" }}(/|$)(.*){{- end }}
        pathType: Prefix
        backend:
          service:
            name: {{ $serviceName }}-nginx
            port:
              number: {{ .Values.nginx.port }}
    host: {{ .Values.ingress.host | quote }}
{{- end -}}
