{{- if .Values.nginx.enabled -}}
{{- $releaseName := .Release.Name -}}
{{- $chartName := include "terrain-server.name" . -}}
{{- $serviceName := include "service.fullname" . -}}
{{- $cloudProviderFlavor := include "terrain-server.cloudProviderFlavor" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}-nginx
  labels:
    app: {{ .Release.Name }}-{{ $chartName }}
    component: terrain-server-nginx-service
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  # In case cloudProavider=azure
  {{- if eq $cloudProviderFlavor "azure" }}
  type: ClusterIP
  {{- end }}
  # In case cloudProvider=minikube
  {{- if eq $cloudProviderFlavor "minikube" }}
  type: NodePort
  {{- end }}
  ports:
    - name: internal
      port: {{ .Values.nginx.internalPort }}
      targetPort: {{ .Values.env.port }}
      protocol: {{ .Values.env.protocol }}
    {{- if .Values.authentication.opa.enabled }}
    - name: external
      port: {{ .Values.nginx.port }}
      targetPort: {{ .Values.envoy.port }}
      protocol: {{ .Values.env.protocol }}
    {{- end }}
      {{- if eq $cloudProviderFlavor "minikube" }}
      nodePort: {{ .Values.nginx.nodePort }}
      {{- end }}
  selector:
    app: {{ .Release.Name }}-{{ $chartName }}
    release: {{ .Release.Name }}
    run: {{ .Release.Name }}-nginx
{{- end }}
