{{- if .Values.nginx.enabled -}}
{{- $chartName := include "terrain-server.name" . -}}
{{- $cloudProviderDockerRegistryUrl := include "terrain-server.cloudProviderDockerRegistryUrl" . -}}
{{- $cloudProviderImagePullSecretName := include "terrain-server.cloudProviderImagePullSecretName" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginx-deployment
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    app: {{ .Release.Name }}-{{ $chartName }}
    component: terrain-server-nginx-deployment
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ $chartName }}
      release: {{ .Release.Name }}
      run: {{ .Release.Name }}-nginx
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ $chartName }}
        release: {{ .Release.Name }}
        run: {{ .Release.Name }}-nginx
      # Autodiscover annotations should be here
      # https://github.com/elastic/beats/issues/7914
      annotations:
        co.elastic.logs/enabled: 'true'
        co.elastic.logs/module: 'nginx'
        co.elastic.logs/fileset.stdout: 'access'
        co.elastic.logs/fileset.stderr: 'error'
        {{- if .Values.resetOnConfigChange }}
        checksum/nginx-configmap: {{ include (print $.Template.BasePath "/nginx-configmap.yaml") . | sha256sum }}
        checksum/envoy-configmap: {{ include (print $.Template.BasePath "/envoy-configmap.yaml") . | sha256sum }}
        {{- end }}
    spec:
    {{- if $cloudProviderImagePullSecretName }}
      imagePullSecrets:
        - name: {{ $cloudProviderImagePullSecretName | quote }}
    {{- end }}
      volumes:
        {{- if .Values.authentication.opa.enabled }}
        - name: opa-policy
          secret:
            secretName: {{ .Release.Name }}-opa
        - name: proxy-config
          configMap:
            name: {{ .Release.Name }}-envoy
        - name: jwt-public-keys
          secret:
            secretName: {{ .Values.authentication.jwtPublicKeySecretName }}
        {{- end }}
        - name: nginx-jwt-js
          configMap:
            name: {{ .Release.Name }}-nginx-configmap
            items:
              - key: jwt.js
                path: jwt.js
        - name: nginx-log-format-conf
          configMap:
            name: {{ .Release.Name }}-nginx-configmap
            items:
              - key: log_format.conf
                path: log_format.conf
        - name: nginx-custom-conf
          configMap:
            name: {{ .Release.Name }}-nginx-configmap
            items:
              - key: default.conf
                path: default.conf
        - name: nginx-root-conf
          configMap:
            name: {{ .Release.Name }}-nginx-configmap
            items:
              - key: nginx.conf
                path: nginx.conf
      containers:
        ## Nginx Deployment
        - name: {{ .Release.Name }}-nginx
          {{- with .Values.nginx.image }}
          image: {{ $cloudProviderDockerRegistryUrl }}{{ .repository }}:{{ .tag }}
          {{- end }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          # command:
          #   - sleep
          #   - infinity
          volumeMounts:
          - name: nginx-jwt-js
            mountPath: /etc/nginx/jwt.js
            subPath: jwt.js
          - name: nginx-log-format-conf
            mountPath: /etc/nginx/log_format.conf
            subPath: log_format.conf
          - name: nginx-custom-conf
            mountPath: /etc/nginx/conf.d
          - name: nginx-root-conf
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
          ports:
            - name: http
              containerPort: {{ .Values.env.port }}
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: {{ .Values.initialDelaySeconds }}
            httpGet:
              path: /liveness
              port: {{ .Values.nginx.port }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.initialDelaySeconds }}
            httpGet:
              path: /liveness
              port: {{ .Values.env.port }}
          {{- if .Values.nginx.resources.enabled }}
          resources:
            {{- toYaml .Values.nginx.resources.value | nindent 12 }}
          {{- end }}
        {{- if .Values.authentication.opa.enabled }}
        - name: envoy
          image: "{{ .Values.envoy.image }}:{{ .Values.envoy.imageTag }}"
          volumeMounts:
          - name: proxy-config
            mountPath: /config
            readOnly: true
          - name: jwt-public-keys
            mountPath: /keys/mapColonies.jwks
            subPath: mapColonies.jwks
            readOnly: true
          args:
          - "envoy"
          - "--config-path"
          - "/config/envoy.yaml"
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          {{- if .Values.envoy.resources.enabled }}
          resources:
            {{- toYaml .Values.envoy.resources.value | nindent 12 }}
          {{- end }}
        - name: opa
          image: "{{ .Values.opa.image }}:{{ .Values.opa.imageTag }}"
          volumeMounts:
          - name: opa-policy
            mountPath: /policy
            readOnly: true
          args:
          - "run"
          - "--server"
          - "--addr=0.0.0.0:8181"
          - "--diagnostic-addr=0.0.0.0:8282"
          - "--set=plugins.envoy_ext_authz_grpc.add=:{{ .Values.opa.imageTag }}"
          - "--set=plugins.envoy_ext_authz_grpc.path=envoy/authz/allow"
          {{- if .Values.opa.enableLogging }}
          - "--set=decision_logs.console=true"
          {{- end }}
          - "/policy/policy.rego"
          {{- if .Values.opa.resources.enabled }}
          resources:
            {{- toYaml .Values.opa.resources.value | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /health?plugins
              port: 8282
            initialDelaySeconds: 5
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health?plugins
              port: 8282
            initialDelaySeconds: 5
            periodSeconds: 30
        {{- end }}
{{- end }}
